# To build a Docker image from this file, run from the root directory:
# docker build -f deployment/Dockerfile-frontend -t ocv .

FROM golang:1.18

# Environment variables
ENV APP_ROOT /src

# Copy source code into container
RUN mkdir --parents $APP_ROOT
WORKDIR $APP_ROOT
COPY src .

# Install dependencies
RUN go mod download

# Build app
RUN go build -o main .

# Expose port
EXPOSE 8080

CMD ["./main"]
