name: Build Docker Images

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  OCV_IMAGE_NAME: ocv
  NGINX_IMAGE_NAME: ocv-nginx

jobs:
  build-ocv-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out Source
        uses: actions/checkout@v2
      - name: Log in to the Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: deployment/Dockerfile-ocv
          push: true
          tags: ghcr.io/sivayogasubramanian/${{ env.OCV_IMAGE_NAME }}:latest

  build-nginx-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out Source
        uses: actions/checkout@v2
      - name: Log in to the Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: deployment/Dockerfile-nginx
          push: true
          tags: ghcr.io/sivayogasubramanian/${{ env.NGINX_IMAGE_NAME }}:latest
